language: node_js

node_js:
  - "0.12"
  - "0.11"
  - "0.10"

branches:
  only:
    - "v2"

services:
  - redis-server

before_install:
  - openssl aes-256-cbc -K $encrypted_c1964ed34d1d_key -iv $encrypted_c1964ed34d1d_iv -in deploy_key.enc -out deploy_key -d

before_script:
  - npm install jshint -g
